use core::str::FromStr;

pub enum Icon {
    Accessibility,
    AddCircle,
    Add,
    Airplane,
    Alarm,
    Albums,
    AlertCircle,
    Alert,
    AmericanFootball,
    Analytics,
    Aperture,
    Apps,
    Archive,
    ArrowBackCircle,
    ArrowBack,
    ArrowDownCircle,
    ArrowDownLeftBox,
    ArrowDownRightBox,
    ArrowDown,
    ArrowForwardCircle,
    ArrowForward,
    ArrowRedoCircle,
    ArrowRedo,
    ArrowUndoCircle,
    ArrowUndo,
    ArrowUpCircle,
    ArrowUpLeftBox,
    ArrowUpRightBox,
    ArrowUp,
    AtCircle,
    At,
    Attach,
    Backspace,
    BagAdd,
    BagCheck,
    BagHandle,
    BagRemove,
    Bag,
    Balloon,
    Ban,
    Bandage,
    BarChart,
    Barbell,
    Barcode,
    Baseball,
    Basket,
    Basketball,
    BatteryCharging,
    BatteryDead,
    BatteryFull,
    BatteryHalf,
    Beaker,
    Bed,
    Beer,
    Bicycle,
    Binoculars,
    Bluetooth,
    Boat,
    Body,
    Bonfire,
    Book,
    Bookmark,
    Bookmarks,
    BowlingBall,
    Briefcase,
    Browsers,
    Brush,
    Bug,
    Build,
    Bulb,
    Bus,
    Business,
    Cafe,
    Calculator,
    CalendarClear,
    CalendarNumber,
    Calendar,
    Call,
    CameraReverse,
    Camera,
    CarSport,
    Car,
    Card,
    CaretBackCircle,
    CaretBack,
    CaretDownCircle,
    CaretDown,
    CaretForwardCircle,
    CaretForward,
    CaretUpCircle,
    CaretUp,
    Cart,
    Cash,
    Cellular,
    ChatboxEllipses,
    Chatbox,
    ChatbubbleEllipses,
    Chatbubble,
    Chatbubbles,
    Checkbox,
    CheckmarkCircle,
    CheckmarkDoneCircle,
    CheckmarkDone,
    Checkmark,
    ChevronBackCircle,
    ChevronBack,
    ChevronCollapse,
    ChevronDownCircle,
    ChevronDown,
    ChevronExpand,
    ChevronForwardCircle,
    ChevronForward,
    ChevronUpCircle,
    ChevronUp,
    Clipboard,
    CloseCircle,
    Close,
    CloudCircle,
    CloudDone,
    CloudDownload,
    CloudOffline,
    CloudUpload,
    Cloud,
    CloudyNight,
    Cloudy,
    CodeDownload,
    CodeSlash,
    CodeWorking,
    Code,
    Cog,
    ColorFill,
    ColorFilter,
    ColorPalette,
    ColorWand,
    Compass,
    Construct,
    Contract,
    Contrast,
    Copy,
    Create,
    Crop,
    Cube,
    Cut,
    Desktop,
    Diamond,
    Dice,
    Disc,
    DocumentAttach,
    DocumentLock,
    DocumentText,
    Document,
    Documents,
    Download,
    Duplicate,
    Ear,
    Earth,
    Easel,
    Egg,
    Ellipse,
    EllipsisHorizontalCircle,
    EllipsisHorizontal,
    EllipsisVerticalCircle,
    EllipsisVertical,
    Enter,
    Exit,
    Expand,
    ExtensionPuzzle,
    EyeOff,
    Eye,
    Eyedrop,
    FastFood,
    Female,
    FileTrayFull,
    FileTrayStacked,
    FileTray,
    Film,
    FilterCircle,
    Filter,
    FingerPrint,
    Fish,
    Fitness,
    Flag,
    Flame,
    FlashOff,
    Flash,
    Flashlight,
    Flask,
    Flower,
    FolderOpen,
    Folder,
    Football,
    Footsteps,
    Funnel,
    GameController,
    Gift,
    GitBranch,
    GitCommit,
    GitCompare,
    GitMerge,
    GitNetwork,
    GitPullRequest,
    Glasses,
    Globe,
    Golf,
    Grid,
    Hammer,
    HandLeft,
    HandRight,
    Happy,
    HardwareChip,
    Headset,
    HeartCircle,
    HeartDislikeCircle,
    HeartDislike,
    HeartHalf,
    Heart,
    HelpBuoy,
    HelpCircle,
    Help,
    Home,
    Hourglass,
    IceCream,
    IdCard,
    Image,
    Images,
    Infinite,
    InformationCircle,
    Information,
    InvertMode,
    Journal,
    Key,
    Keypad,
    Language,
    Laptop,
    Layers,
    Leaf,
    Library,
    Link,
    ListCircle,
    List,
    Locate,
    Location,
    LockClosed,
    LockOpen,
    LogIn,
    LogOut,
    LogoAlipay,
    LogoAmazon,
    LogoAmplify,
    LogoAndroid,
    LogoAngular,
    LogoAppflow,
    LogoAppleAppstore,
    LogoAppleAr,
    LogoApple,
    LogoBehance,
    LogoBitbucket,
    LogoBitcoin,
    LogoBuffer,
    LogoCapacitor,
    LogoChrome,
    LogoClosedCaptioning,
    LogoCodepen,
    LogoCss3,
    LogoDesignernews,
    LogoDeviantart,
    LogoDiscord,
    LogoDocker,
    LogoDribbble,
    LogoDropbox,
    LogoEdge,
    LogoElectron,
    LogoEuro,
    LogoFacebook,
    LogoFigma,
    LogoFirebase,
    LogoFirefox,
    LogoFlickr,
    LogoFoursquare,
    LogoGithub,
    LogoGitlab,
    LogoGooglePlaystore,
    LogoGoogle,
    LogoHackernews,
    LogoHtml5,
    LogoInstagram,
    LogoIonic,
    LogoIonitron,
    LogoJavascript,
    LogoLaravel,
    LogoLinkedin,
    LogoMarkdown,
    LogoMastodon,
    LogoMedium,
    LogoMicrosoft,
    LogoNoSmoking,
    LogoNodejs,
    LogoNpm,
    LogoOctocat,
    LogoPaypal,
    LogoPinterest,
    LogoPlaystation,
    LogoPwa,
    LogoPython,
    LogoReact,
    LogoReddit,
    LogoRss,
    LogoSass,
    LogoSkype,
    LogoSlack,
    LogoSnapchat,
    LogoSoundcloud,
    LogoStackoverflow,
    LogoSteam,
    LogoStencil,
    LogoTableau,
    LogoTiktok,
    LogoTrapeze,
    LogoTumblr,
    LogoTux,
    LogoTwitch,
    LogoTwitter,
    LogoUsd,
    LogoVenmo,
    LogoVercel,
    LogoVimeo,
    LogoVk,
    LogoVue,
    LogoWebComponent,
    LogoWechat,
    LogoWhatsapp,
    LogoWindows,
    LogoWordpress,
    LogoX,
    LogoXbox,
    LogoXing,
    LogoYahoo,
    LogoYen,
    LogoYoutube,
    Magnet,
    MailOpen,
    MailUnread,
    Mail,
    MaleFemale,
    Male,
    Man,
    Map,
    Medal,
    Medical,
    Medkit,
    Megaphone,
    Menu,
    MicCircle,
    MicOffCircle,
    MicOff,
    Mic,
    Moon,
    Move,
    MusicalNote,
    MusicalNotes,
    NavigateCircle,
    Navigate,
    Newspaper,
    NotificationsCircle,
    NotificationsOffCircle,
    NotificationsOff,
    Notifications,
    Nuclear,
    Nutrition,
    Open,
    Options,
    PaperPlane,
    PartlySunny,
    PauseCircle,
    Pause,
    Paw,
    Pencil,
    PeopleCircle,
    People,
    PersonAdd,
    PersonCircle,
    PersonRemove,
    Person,
    PhoneLandscape,
    PhonePortrait,
    PieChart,
    Pin,
    Pint,
    Pizza,
    Planet,
    PlayBackCircle,
    PlayBack,
    PlayCircle,
    PlayForwardCircle,
    PlayForward,
    PlaySkipBackCircle,
    PlaySkipBack,
    PlaySkipForwardCircle,
    PlaySkipForward,
    Play,
    Podium,
    Power,
    Pricetag,
    Pricetags,
    Print,
    Prism,
    Pulse,
    Push,
    QrCode,
    RadioButtonOff,
    RadioButtonOn,
    Radio,
    Rainy,
    Reader,
    Receipt,
    Recording,
    RefreshCircle,
    Refresh,
    ReloadCircle,
    Reload,
    RemoveCircle,
    Remove,
    ReorderFour,
    ReorderThree,
    ReorderTwo,
    Repeat,
    Resize,
    Restaurant,
    ReturnDownBack,
    ReturnDownForward,
    ReturnUpBack,
    ReturnUpForward,
    Ribbon,
    Rocket,
    Rose,
    Sad,
    Save,
    Scale,
    ScanCircle,
    Scan,
    School,
    SearchCircle,
    Search,
    Send,
    Server,
    Settings,
    Shapes,
    ShareSocial,
    Share,
    ShieldCheckmark,
    ShieldHalf,
    Shield,
    Shirt,
    Shuffle,
    Skull,
    Snow,
    Sparkles,
    Speedometer,
    Square,
    StarHalf,
    Star,
    StatsChart,
    StopCircle,
    Stop,
    Stopwatch,
    Storefront,
    Subway,
    Sunny,
    SwapHorizontal,
    SwapVertical,
    SyncCircle,
    Sync,
    TabletLandscape,
    TabletPortrait,
    Telescope,
    Tennisball,
    Terminal,
    Text,
    Thermometer,
    ThumbsDown,
    ThumbsUp,
    Thunderstorm,
    Ticket,
    Time,
    Timer,
    Today,
    Toggle,
    TrailSign,
    Train,
    Transgender,
    TrashBin,
    Trash,
    TrendingDown,
    TrendingUp,
    Triangle,
    Trophy,
    Tv,
    Umbrella,
    Unlink,
    VideocamOff,
    Videocam,
    VolumeHigh,
    VolumeLow,
    VolumeMedium,
    VolumeMute,
    VolumeOff,
    Walk,
    Wallet,
    Warning,
    Watch,
    Water,
    Wifi,
    Wine,
    Woman,
}

impl FromStr for Icon {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "accessibility" => Ok(Self::Accessibility),
            "add-circle" => Ok(Self::AddCircle),
            "add" => Ok(Self::Add),
            "airplane" => Ok(Self::Airplane),
            "alarm" => Ok(Self::Alarm),
            "albums" => Ok(Self::Albums),
            "alert-circle" => Ok(Self::AlertCircle),
            "alert" => Ok(Self::Alert),
            "american-football" => Ok(Self::AmericanFootball),
            "analytics" => Ok(Self::Analytics),
            "aperture" => Ok(Self::Aperture),
            "apps" => Ok(Self::Apps),
            "archive" => Ok(Self::Archive),
            "arrow-back-circle" => Ok(Self::ArrowBackCircle),
            "arrow-back" => Ok(Self::ArrowBack),
            "arrow-down-circle" => Ok(Self::ArrowDownCircle),
            "arrow-down-left-box" => Ok(Self::ArrowDownLeftBox),
            "arrow-down-right-box" => Ok(Self::ArrowDownRightBox),
            "arrow-down" => Ok(Self::ArrowDown),
            "arrow-forward-circle" => Ok(Self::ArrowForwardCircle),
            "arrow-forward" => Ok(Self::ArrowForward),
            "arrow-redo-circle" => Ok(Self::ArrowRedoCircle),
            "arrow-redo" => Ok(Self::ArrowRedo),
            "arrow-undo-circle" => Ok(Self::ArrowUndoCircle),
            "arrow-undo" => Ok(Self::ArrowUndo),
            "arrow-up-circle" => Ok(Self::ArrowUpCircle),
            "arrow-up-left-box" => Ok(Self::ArrowUpLeftBox),
            "arrow-up-right-box" => Ok(Self::ArrowUpRightBox),
            "arrow-up" => Ok(Self::ArrowUp),
            "at-circle" => Ok(Self::AtCircle),
            "at" => Ok(Self::At),
            "attach" => Ok(Self::Attach),
            "backspace" => Ok(Self::Backspace),
            "bag-add" => Ok(Self::BagAdd),
            "bag-check" => Ok(Self::BagCheck),
            "bag-handle" => Ok(Self::BagHandle),
            "bag-remove" => Ok(Self::BagRemove),
            "bag" => Ok(Self::Bag),
            "balloon" => Ok(Self::Balloon),
            "ban" => Ok(Self::Ban),
            "bandage" => Ok(Self::Bandage),
            "bar-chart" => Ok(Self::BarChart),
            "barbell" => Ok(Self::Barbell),
            "barcode" => Ok(Self::Barcode),
            "baseball" => Ok(Self::Baseball),
            "basket" => Ok(Self::Basket),
            "basketball" => Ok(Self::Basketball),
            "battery-charging" => Ok(Self::BatteryCharging),
            "battery-dead" => Ok(Self::BatteryDead),
            "battery-full" => Ok(Self::BatteryFull),
            "battery-half" => Ok(Self::BatteryHalf),
            "beaker" => Ok(Self::Beaker),
            "bed" => Ok(Self::Bed),
            "beer" => Ok(Self::Beer),
            "bicycle" => Ok(Self::Bicycle),
            "binoculars" => Ok(Self::Binoculars),
            "bluetooth" => Ok(Self::Bluetooth),
            "boat" => Ok(Self::Boat),
            "body" => Ok(Self::Body),
            "bonfire" => Ok(Self::Bonfire),
            "book" => Ok(Self::Book),
            "bookmark" => Ok(Self::Bookmark),
            "bookmarks" => Ok(Self::Bookmarks),
            "bowling-ball" => Ok(Self::BowlingBall),
            "briefcase" => Ok(Self::Briefcase),
            "browsers" => Ok(Self::Browsers),
            "brush" => Ok(Self::Brush),
            "bug" => Ok(Self::Bug),
            "build" => Ok(Self::Build),
            "bulb" => Ok(Self::Bulb),
            "bus" => Ok(Self::Bus),
            "business" => Ok(Self::Business),
            "cafe" => Ok(Self::Cafe),
            "calculator" => Ok(Self::Calculator),
            "calendar-clear" => Ok(Self::CalendarClear),
            "calendar-number" => Ok(Self::CalendarNumber),
            "calendar" => Ok(Self::Calendar),
            "call" => Ok(Self::Call),
            "camera-reverse" => Ok(Self::CameraReverse),
            "camera" => Ok(Self::Camera),
            "car-sport" => Ok(Self::CarSport),
            "car" => Ok(Self::Car),
            "card" => Ok(Self::Card),
            "caret-back-circle" => Ok(Self::CaretBackCircle),
            "caret-back" => Ok(Self::CaretBack),
            "caret-down-circle" => Ok(Self::CaretDownCircle),
            "caret-down" => Ok(Self::CaretDown),
            "caret-forward-circle" => Ok(Self::CaretForwardCircle),
            "caret-forward" => Ok(Self::CaretForward),
            "caret-up-circle" => Ok(Self::CaretUpCircle),
            "caret-up" => Ok(Self::CaretUp),
            "cart" => Ok(Self::Cart),
            "cash" => Ok(Self::Cash),
            "cellular" => Ok(Self::Cellular),
            "chatbox-ellipses" => Ok(Self::ChatboxEllipses),
            "chatbox" => Ok(Self::Chatbox),
            "chatbubble-ellipses" => Ok(Self::ChatbubbleEllipses),
            "chatbubble" => Ok(Self::Chatbubble),
            "chatbubbles" => Ok(Self::Chatbubbles),
            "checkbox" => Ok(Self::Checkbox),
            "checkmark-circle" => Ok(Self::CheckmarkCircle),
            "checkmark-done-circle" => Ok(Self::CheckmarkDoneCircle),
            "checkmark-done" => Ok(Self::CheckmarkDone),
            "checkmark" => Ok(Self::Checkmark),
            "chevron-back-circle" => Ok(Self::ChevronBackCircle),
            "chevron-back" => Ok(Self::ChevronBack),
            "chevron-collapse" => Ok(Self::ChevronCollapse),
            "chevron-down-circle" => Ok(Self::ChevronDownCircle),
            "chevron-down" => Ok(Self::ChevronDown),
            "chevron-expand" => Ok(Self::ChevronExpand),
            "chevron-forward-circle" => Ok(Self::ChevronForwardCircle),
            "chevron-forward" => Ok(Self::ChevronForward),
            "chevron-up-circle" => Ok(Self::ChevronUpCircle),
            "chevron-up" => Ok(Self::ChevronUp),
            "clipboard" => Ok(Self::Clipboard),
            "close-circle" => Ok(Self::CloseCircle),
            "close" => Ok(Self::Close),
            "cloud-circle" => Ok(Self::CloudCircle),
            "cloud-done" => Ok(Self::CloudDone),
            "cloud-download" => Ok(Self::CloudDownload),
            "cloud-offline" => Ok(Self::CloudOffline),
            "cloud-upload" => Ok(Self::CloudUpload),
            "cloud" => Ok(Self::Cloud),
            "cloudy-night" => Ok(Self::CloudyNight),
            "cloudy" => Ok(Self::Cloudy),
            "code-download" => Ok(Self::CodeDownload),
            "code-slash" => Ok(Self::CodeSlash),
            "code-working" => Ok(Self::CodeWorking),
            "code" => Ok(Self::Code),
            "cog" => Ok(Self::Cog),
            "color-fill" => Ok(Self::ColorFill),
            "color-filter" => Ok(Self::ColorFilter),
            "color-palette" => Ok(Self::ColorPalette),
            "color-wand" => Ok(Self::ColorWand),
            "compass" => Ok(Self::Compass),
            "construct" => Ok(Self::Construct),
            "contract" => Ok(Self::Contract),
            "contrast" => Ok(Self::Contrast),
            "copy" => Ok(Self::Copy),
            "create" => Ok(Self::Create),
            "crop" => Ok(Self::Crop),
            "cube" => Ok(Self::Cube),
            "cut" => Ok(Self::Cut),
            "desktop" => Ok(Self::Desktop),
            "diamond" => Ok(Self::Diamond),
            "dice" => Ok(Self::Dice),
            "disc" => Ok(Self::Disc),
            "document-attach" => Ok(Self::DocumentAttach),
            "document-lock" => Ok(Self::DocumentLock),
            "document-text" => Ok(Self::DocumentText),
            "document" => Ok(Self::Document),
            "documents" => Ok(Self::Documents),
            "download" => Ok(Self::Download),
            "duplicate" => Ok(Self::Duplicate),
            "ear" => Ok(Self::Ear),
            "earth" => Ok(Self::Earth),
            "easel" => Ok(Self::Easel),
            "egg" => Ok(Self::Egg),
            "ellipse" => Ok(Self::Ellipse),
            "ellipsis-horizontal-circle" => Ok(Self::EllipsisHorizontalCircle),
            "ellipsis-horizontal" => Ok(Self::EllipsisHorizontal),
            "ellipsis-vertical-circle" => Ok(Self::EllipsisVerticalCircle),
            "ellipsis-vertical" => Ok(Self::EllipsisVertical),
            "enter" => Ok(Self::Enter),
            "exit" => Ok(Self::Exit),
            "expand" => Ok(Self::Expand),
            "extension-puzzle" => Ok(Self::ExtensionPuzzle),
            "eye-off" => Ok(Self::EyeOff),
            "eye" => Ok(Self::Eye),
            "eyedrop" => Ok(Self::Eyedrop),
            "fast-food" => Ok(Self::FastFood),
            "female" => Ok(Self::Female),
            "file-tray-full" => Ok(Self::FileTrayFull),
            "file-tray-stacked" => Ok(Self::FileTrayStacked),
            "file-tray" => Ok(Self::FileTray),
            "film" => Ok(Self::Film),
            "filter-circle" => Ok(Self::FilterCircle),
            "filter" => Ok(Self::Filter),
            "finger-print" => Ok(Self::FingerPrint),
            "fish" => Ok(Self::Fish),
            "fitness" => Ok(Self::Fitness),
            "flag" => Ok(Self::Flag),
            "flame" => Ok(Self::Flame),
            "flash-off" => Ok(Self::FlashOff),
            "flash" => Ok(Self::Flash),
            "flashlight" => Ok(Self::Flashlight),
            "flask" => Ok(Self::Flask),
            "flower" => Ok(Self::Flower),
            "folder-open" => Ok(Self::FolderOpen),
            "folder" => Ok(Self::Folder),
            "football" => Ok(Self::Football),
            "footsteps" => Ok(Self::Footsteps),
            "funnel" => Ok(Self::Funnel),
            "game-controller" => Ok(Self::GameController),
            "gift" => Ok(Self::Gift),
            "git-branch" => Ok(Self::GitBranch),
            "git-commit" => Ok(Self::GitCommit),
            "git-compare" => Ok(Self::GitCompare),
            "git-merge" => Ok(Self::GitMerge),
            "git-network" => Ok(Self::GitNetwork),
            "git-pull-request" => Ok(Self::GitPullRequest),
            "glasses" => Ok(Self::Glasses),
            "globe" => Ok(Self::Globe),
            "golf" => Ok(Self::Golf),
            "grid" => Ok(Self::Grid),
            "hammer" => Ok(Self::Hammer),
            "hand-left" => Ok(Self::HandLeft),
            "hand-right" => Ok(Self::HandRight),
            "happy" => Ok(Self::Happy),
            "hardware-chip" => Ok(Self::HardwareChip),
            "headset" => Ok(Self::Headset),
            "heart-circle" => Ok(Self::HeartCircle),
            "heart-dislike-circle" => Ok(Self::HeartDislikeCircle),
            "heart-dislike" => Ok(Self::HeartDislike),
            "heart-half" => Ok(Self::HeartHalf),
            "heart" => Ok(Self::Heart),
            "help-buoy" => Ok(Self::HelpBuoy),
            "help-circle" => Ok(Self::HelpCircle),
            "help" => Ok(Self::Help),
            "home" => Ok(Self::Home),
            "hourglass" => Ok(Self::Hourglass),
            "ice-cream" => Ok(Self::IceCream),
            "id-card" => Ok(Self::IdCard),
            "image" => Ok(Self::Image),
            "images" => Ok(Self::Images),
            "infinite" => Ok(Self::Infinite),
            "information-circle" => Ok(Self::InformationCircle),
            "information" => Ok(Self::Information),
            "invert-mode" => Ok(Self::InvertMode),
            "journal" => Ok(Self::Journal),
            "key" => Ok(Self::Key),
            "keypad" => Ok(Self::Keypad),
            "language" => Ok(Self::Language),
            "laptop" => Ok(Self::Laptop),
            "layers" => Ok(Self::Layers),
            "leaf" => Ok(Self::Leaf),
            "library" => Ok(Self::Library),
            "link" => Ok(Self::Link),
            "list-circle" => Ok(Self::ListCircle),
            "list" => Ok(Self::List),
            "locate" => Ok(Self::Locate),
            "location" => Ok(Self::Location),
            "lock-closed" => Ok(Self::LockClosed),
            "lock-open" => Ok(Self::LockOpen),
            "log-in" => Ok(Self::LogIn),
            "log-out" => Ok(Self::LogOut),
            "logo-alipay" => Ok(Self::LogoAlipay),
            "logo-amazon" => Ok(Self::LogoAmazon),
            "logo-amplify" => Ok(Self::LogoAmplify),
            "logo-android" => Ok(Self::LogoAndroid),
            "logo-angular" => Ok(Self::LogoAngular),
            "logo-appflow" => Ok(Self::LogoAppflow),
            "logo-apple-appstore" => Ok(Self::LogoAppleAppstore),
            "logo-apple-ar" => Ok(Self::LogoAppleAr),
            "logo-apple" => Ok(Self::LogoApple),
            "logo-behance" => Ok(Self::LogoBehance),
            "logo-bitbucket" => Ok(Self::LogoBitbucket),
            "logo-bitcoin" => Ok(Self::LogoBitcoin),
            "logo-buffer" => Ok(Self::LogoBuffer),
            "logo-capacitor" => Ok(Self::LogoCapacitor),
            "logo-chrome" => Ok(Self::LogoChrome),
            "logo-closed-captioning" => Ok(Self::LogoClosedCaptioning),
            "logo-codepen" => Ok(Self::LogoCodepen),
            "logo-css3" => Ok(Self::LogoCss3),
            "logo-designernews" => Ok(Self::LogoDesignernews),
            "logo-deviantart" => Ok(Self::LogoDeviantart),
            "logo-discord" => Ok(Self::LogoDiscord),
            "logo-docker" => Ok(Self::LogoDocker),
            "logo-dribbble" => Ok(Self::LogoDribbble),
            "logo-dropbox" => Ok(Self::LogoDropbox),
            "logo-edge" => Ok(Self::LogoEdge),
            "logo-electron" => Ok(Self::LogoElectron),
            "logo-euro" => Ok(Self::LogoEuro),
            "logo-facebook" => Ok(Self::LogoFacebook),
            "logo-figma" => Ok(Self::LogoFigma),
            "logo-firebase" => Ok(Self::LogoFirebase),
            "logo-firefox" => Ok(Self::LogoFirefox),
            "logo-flickr" => Ok(Self::LogoFlickr),
            "logo-foursquare" => Ok(Self::LogoFoursquare),
            "logo-github" => Ok(Self::LogoGithub),
            "logo-gitlab" => Ok(Self::LogoGitlab),
            "logo-google-playstore" => Ok(Self::LogoGooglePlaystore),
            "logo-google" => Ok(Self::LogoGoogle),
            "logo-hackernews" => Ok(Self::LogoHackernews),
            "logo-html5" => Ok(Self::LogoHtml5),
            "logo-instagram" => Ok(Self::LogoInstagram),
            "logo-ionic" => Ok(Self::LogoIonic),
            "logo-ionitron" => Ok(Self::LogoIonitron),
            "logo-javascript" => Ok(Self::LogoJavascript),
            "logo-laravel" => Ok(Self::LogoLaravel),
            "logo-linkedin" => Ok(Self::LogoLinkedin),
            "logo-markdown" => Ok(Self::LogoMarkdown),
            "logo-mastodon" => Ok(Self::LogoMastodon),
            "logo-medium" => Ok(Self::LogoMedium),
            "logo-microsoft" => Ok(Self::LogoMicrosoft),
            "logo-no-smoking" => Ok(Self::LogoNoSmoking),
            "logo-nodejs" => Ok(Self::LogoNodejs),
            "logo-npm" => Ok(Self::LogoNpm),
            "logo-octocat" => Ok(Self::LogoOctocat),
            "logo-paypal" => Ok(Self::LogoPaypal),
            "logo-pinterest" => Ok(Self::LogoPinterest),
            "logo-playstation" => Ok(Self::LogoPlaystation),
            "logo-pwa" => Ok(Self::LogoPwa),
            "logo-python" => Ok(Self::LogoPython),
            "logo-react" => Ok(Self::LogoReact),
            "logo-reddit" => Ok(Self::LogoReddit),
            "logo-rss" => Ok(Self::LogoRss),
            "logo-sass" => Ok(Self::LogoSass),
            "logo-skype" => Ok(Self::LogoSkype),
            "logo-slack" => Ok(Self::LogoSlack),
            "logo-snapchat" => Ok(Self::LogoSnapchat),
            "logo-soundcloud" => Ok(Self::LogoSoundcloud),
            "logo-stackoverflow" => Ok(Self::LogoStackoverflow),
            "logo-steam" => Ok(Self::LogoSteam),
            "logo-stencil" => Ok(Self::LogoStencil),
            "logo-tableau" => Ok(Self::LogoTableau),
            "logo-tiktok" => Ok(Self::LogoTiktok),
            "logo-trapeze" => Ok(Self::LogoTrapeze),
            "logo-tumblr" => Ok(Self::LogoTumblr),
            "logo-tux" => Ok(Self::LogoTux),
            "logo-twitch" => Ok(Self::LogoTwitch),
            "logo-twitter" => Ok(Self::LogoTwitter),
            "logo-usd" => Ok(Self::LogoUsd),
            "logo-venmo" => Ok(Self::LogoVenmo),
            "logo-vercel" => Ok(Self::LogoVercel),
            "logo-vimeo" => Ok(Self::LogoVimeo),
            "logo-vk" => Ok(Self::LogoVk),
            "logo-vue" => Ok(Self::LogoVue),
            "logo-web-component" => Ok(Self::LogoWebComponent),
            "logo-wechat" => Ok(Self::LogoWechat),
            "logo-whatsapp" => Ok(Self::LogoWhatsapp),
            "logo-windows" => Ok(Self::LogoWindows),
            "logo-wordpress" => Ok(Self::LogoWordpress),
            "logo-x" => Ok(Self::LogoX),
            "logo-xbox" => Ok(Self::LogoXbox),
            "logo-xing" => Ok(Self::LogoXing),
            "logo-yahoo" => Ok(Self::LogoYahoo),
            "logo-yen" => Ok(Self::LogoYen),
            "logo-youtube" => Ok(Self::LogoYoutube),
            "magnet" => Ok(Self::Magnet),
            "mail-open" => Ok(Self::MailOpen),
            "mail-unread" => Ok(Self::MailUnread),
            "mail" => Ok(Self::Mail),
            "male-female" => Ok(Self::MaleFemale),
            "male" => Ok(Self::Male),
            "man" => Ok(Self::Man),
            "map" => Ok(Self::Map),
            "medal" => Ok(Self::Medal),
            "medical" => Ok(Self::Medical),
            "medkit" => Ok(Self::Medkit),
            "megaphone" => Ok(Self::Megaphone),
            "menu" => Ok(Self::Menu),
            "mic-circle" => Ok(Self::MicCircle),
            "mic-off-circle" => Ok(Self::MicOffCircle),
            "mic-off" => Ok(Self::MicOff),
            "mic" => Ok(Self::Mic),
            "moon" => Ok(Self::Moon),
            "move" => Ok(Self::Move),
            "musical-note" => Ok(Self::MusicalNote),
            "musical-notes" => Ok(Self::MusicalNotes),
            "navigate-circle" => Ok(Self::NavigateCircle),
            "navigate" => Ok(Self::Navigate),
            "newspaper" => Ok(Self::Newspaper),
            "notifications-circle" => Ok(Self::NotificationsCircle),
            "notifications-off-circle" => Ok(Self::NotificationsOffCircle),
            "notifications-off" => Ok(Self::NotificationsOff),
            "notifications" => Ok(Self::Notifications),
            "nuclear" => Ok(Self::Nuclear),
            "nutrition" => Ok(Self::Nutrition),
            "open" => Ok(Self::Open),
            "options" => Ok(Self::Options),
            "paper-plane" => Ok(Self::PaperPlane),
            "partly-sunny" => Ok(Self::PartlySunny),
            "pause-circle" => Ok(Self::PauseCircle),
            "pause" => Ok(Self::Pause),
            "paw" => Ok(Self::Paw),
            "pencil" => Ok(Self::Pencil),
            "people-circle" => Ok(Self::PeopleCircle),
            "people" => Ok(Self::People),
            "person-add" => Ok(Self::PersonAdd),
            "person-circle" => Ok(Self::PersonCircle),
            "person-remove" => Ok(Self::PersonRemove),
            "person" => Ok(Self::Person),
            "phone-landscape" => Ok(Self::PhoneLandscape),
            "phone-portrait" => Ok(Self::PhonePortrait),
            "pie-chart" => Ok(Self::PieChart),
            "pin" => Ok(Self::Pin),
            "pint" => Ok(Self::Pint),
            "pizza" => Ok(Self::Pizza),
            "planet" => Ok(Self::Planet),
            "play-back-circle" => Ok(Self::PlayBackCircle),
            "play-back" => Ok(Self::PlayBack),
            "play-circle" => Ok(Self::PlayCircle),
            "play-forward-circle" => Ok(Self::PlayForwardCircle),
            "play-forward" => Ok(Self::PlayForward),
            "play-skip-back-circle" => Ok(Self::PlaySkipBackCircle),
            "play-skip-back" => Ok(Self::PlaySkipBack),
            "play-skip-forward-circle" => Ok(Self::PlaySkipForwardCircle),
            "play-skip-forward" => Ok(Self::PlaySkipForward),
            "play" => Ok(Self::Play),
            "podium" => Ok(Self::Podium),
            "power" => Ok(Self::Power),
            "pricetag" => Ok(Self::Pricetag),
            "pricetags" => Ok(Self::Pricetags),
            "print" => Ok(Self::Print),
            "prism" => Ok(Self::Prism),
            "pulse" => Ok(Self::Pulse),
            "push" => Ok(Self::Push),
            "qr-code" => Ok(Self::QrCode),
            "radio-button-off" => Ok(Self::RadioButtonOff),
            "radio-button-on" => Ok(Self::RadioButtonOn),
            "radio" => Ok(Self::Radio),
            "rainy" => Ok(Self::Rainy),
            "reader" => Ok(Self::Reader),
            "receipt" => Ok(Self::Receipt),
            "recording" => Ok(Self::Recording),
            "refresh-circle" => Ok(Self::RefreshCircle),
            "refresh" => Ok(Self::Refresh),
            "reload-circle" => Ok(Self::ReloadCircle),
            "reload" => Ok(Self::Reload),
            "remove-circle" => Ok(Self::RemoveCircle),
            "remove" => Ok(Self::Remove),
            "reorder-four" => Ok(Self::ReorderFour),
            "reorder-three" => Ok(Self::ReorderThree),
            "reorder-two" => Ok(Self::ReorderTwo),
            "repeat" => Ok(Self::Repeat),
            "resize" => Ok(Self::Resize),
            "restaurant" => Ok(Self::Restaurant),
            "return-down-back" => Ok(Self::ReturnDownBack),
            "return-down-forward" => Ok(Self::ReturnDownForward),
            "return-up-back" => Ok(Self::ReturnUpBack),
            "return-up-forward" => Ok(Self::ReturnUpForward),
            "ribbon" => Ok(Self::Ribbon),
            "rocket" => Ok(Self::Rocket),
            "rose" => Ok(Self::Rose),
            "sad" => Ok(Self::Sad),
            "save" => Ok(Self::Save),
            "scale" => Ok(Self::Scale),
            "scan-circle" => Ok(Self::ScanCircle),
            "scan" => Ok(Self::Scan),
            "school" => Ok(Self::School),
            "search-circle" => Ok(Self::SearchCircle),
            "search" => Ok(Self::Search),
            "send" => Ok(Self::Send),
            "server" => Ok(Self::Server),
            "settings" => Ok(Self::Settings),
            "shapes" => Ok(Self::Shapes),
            "share-social" => Ok(Self::ShareSocial),
            "share" => Ok(Self::Share),
            "shield-checkmark" => Ok(Self::ShieldCheckmark),
            "shield-half" => Ok(Self::ShieldHalf),
            "shield" => Ok(Self::Shield),
            "shirt" => Ok(Self::Shirt),
            "shuffle" => Ok(Self::Shuffle),
            "skull" => Ok(Self::Skull),
            "snow" => Ok(Self::Snow),
            "sparkles" => Ok(Self::Sparkles),
            "speedometer" => Ok(Self::Speedometer),
            "square" => Ok(Self::Square),
            "star-half" => Ok(Self::StarHalf),
            "star" => Ok(Self::Star),
            "stats-chart" => Ok(Self::StatsChart),
            "stop-circle" => Ok(Self::StopCircle),
            "stop" => Ok(Self::Stop),
            "stopwatch" => Ok(Self::Stopwatch),
            "storefront" => Ok(Self::Storefront),
            "subway" => Ok(Self::Subway),
            "sunny" => Ok(Self::Sunny),
            "swap-horizontal" => Ok(Self::SwapHorizontal),
            "swap-vertical" => Ok(Self::SwapVertical),
            "sync-circle" => Ok(Self::SyncCircle),
            "sync" => Ok(Self::Sync),
            "tablet-landscape" => Ok(Self::TabletLandscape),
            "tablet-portrait" => Ok(Self::TabletPortrait),
            "telescope" => Ok(Self::Telescope),
            "tennisball" => Ok(Self::Tennisball),
            "terminal" => Ok(Self::Terminal),
            "text" => Ok(Self::Text),
            "thermometer" => Ok(Self::Thermometer),
            "thumbs-down" => Ok(Self::ThumbsDown),
            "thumbs-up" => Ok(Self::ThumbsUp),
            "thunderstorm" => Ok(Self::Thunderstorm),
            "ticket" => Ok(Self::Ticket),
            "time" => Ok(Self::Time),
            "timer" => Ok(Self::Timer),
            "today" => Ok(Self::Today),
            "toggle" => Ok(Self::Toggle),
            "trail-sign" => Ok(Self::TrailSign),
            "train" => Ok(Self::Train),
            "transgender" => Ok(Self::Transgender),
            "trash-bin" => Ok(Self::TrashBin),
            "trash" => Ok(Self::Trash),
            "trending-down" => Ok(Self::TrendingDown),
            "trending-up" => Ok(Self::TrendingUp),
            "triangle" => Ok(Self::Triangle),
            "trophy" => Ok(Self::Trophy),
            "tv" => Ok(Self::Tv),
            "umbrella" => Ok(Self::Umbrella),
            "unlink" => Ok(Self::Unlink),
            "videocam-off" => Ok(Self::VideocamOff),
            "videocam" => Ok(Self::Videocam),
            "volume-high" => Ok(Self::VolumeHigh),
            "volume-low" => Ok(Self::VolumeLow),
            "volume-medium" => Ok(Self::VolumeMedium),
            "volume-mute" => Ok(Self::VolumeMute),
            "volume-off" => Ok(Self::VolumeOff),
            "walk" => Ok(Self::Walk),
            "wallet" => Ok(Self::Wallet),
            "warning" => Ok(Self::Warning),
            "watch" => Ok(Self::Watch),
            "water" => Ok(Self::Water),
            "wifi" => Ok(Self::Wifi),
            "wine" => Ok(Self::Wine),
            "woman" => Ok(Self::Woman),
            _ => Err(()),
        }
    }
}

impl Icon {
    pub fn svg(&self) -> &'static str {
        match self {
            Self::Accessibility => include_str!("icons/accessibility.svg"),
            Self::AddCircle => include_str!("icons/add-circle.svg"),
            Self::Add => include_str!("icons/add.svg"),
            Self::Airplane => include_str!("icons/airplane.svg"),
            Self::Alarm => include_str!("icons/alarm.svg"),
            Self::Albums => include_str!("icons/albums.svg"),
            Self::AlertCircle => include_str!("icons/alert-circle.svg"),
            Self::Alert => include_str!("icons/alert.svg"),
            Self::AmericanFootball => include_str!("icons/american-football.svg"),
            Self::Analytics => include_str!("icons/analytics.svg"),
            Self::Aperture => include_str!("icons/aperture.svg"),
            Self::Apps => include_str!("icons/apps.svg"),
            Self::Archive => include_str!("icons/archive.svg"),
            Self::ArrowBackCircle => include_str!("icons/arrow-back-circle.svg"),
            Self::ArrowBack => include_str!("icons/arrow-back.svg"),
            Self::ArrowDownCircle => include_str!("icons/arrow-down-circle.svg"),
            Self::ArrowDownLeftBox => include_str!("icons/arrow-down-left-box.svg"),
            Self::ArrowDownRightBox => include_str!("icons/arrow-down-right-box.svg"),
            Self::ArrowDown => include_str!("icons/arrow-down.svg"),
            Self::ArrowForwardCircle => include_str!("icons/arrow-forward-circle.svg"),
            Self::ArrowForward => include_str!("icons/arrow-forward.svg"),
            Self::ArrowRedoCircle => include_str!("icons/arrow-redo-circle.svg"),
            Self::ArrowRedo => include_str!("icons/arrow-redo.svg"),
            Self::ArrowUndoCircle => include_str!("icons/arrow-undo-circle.svg"),
            Self::ArrowUndo => include_str!("icons/arrow-undo.svg"),
            Self::ArrowUpCircle => include_str!("icons/arrow-up-circle.svg"),
            Self::ArrowUpLeftBox => include_str!("icons/arrow-up-left-box.svg"),
            Self::ArrowUpRightBox => include_str!("icons/arrow-up-right-box.svg"),
            Self::ArrowUp => include_str!("icons/arrow-up.svg"),
            Self::AtCircle => include_str!("icons/at-circle.svg"),
            Self::At => include_str!("icons/at.svg"),
            Self::Attach => include_str!("icons/attach.svg"),
            Self::Backspace => include_str!("icons/backspace.svg"),
            Self::BagAdd => include_str!("icons/bag-add.svg"),
            Self::BagCheck => include_str!("icons/bag-check.svg"),
            Self::BagHandle => include_str!("icons/bag-handle.svg"),
            Self::BagRemove => include_str!("icons/bag-remove.svg"),
            Self::Bag => include_str!("icons/bag.svg"),
            Self::Balloon => include_str!("icons/balloon.svg"),
            Self::Ban => include_str!("icons/ban.svg"),
            Self::Bandage => include_str!("icons/bandage.svg"),
            Self::BarChart => include_str!("icons/bar-chart.svg"),
            Self::Barbell => include_str!("icons/barbell.svg"),
            Self::Barcode => include_str!("icons/barcode.svg"),
            Self::Baseball => include_str!("icons/baseball.svg"),
            Self::Basket => include_str!("icons/basket.svg"),
            Self::Basketball => include_str!("icons/basketball.svg"),
            Self::BatteryCharging => include_str!("icons/battery-charging.svg"),
            Self::BatteryDead => include_str!("icons/battery-dead.svg"),
            Self::BatteryFull => include_str!("icons/battery-full.svg"),
            Self::BatteryHalf => include_str!("icons/battery-half.svg"),
            Self::Beaker => include_str!("icons/beaker.svg"),
            Self::Bed => include_str!("icons/bed.svg"),
            Self::Beer => include_str!("icons/beer.svg"),
            Self::Bicycle => include_str!("icons/bicycle.svg"),
            Self::Binoculars => include_str!("icons/binoculars.svg"),
            Self::Bluetooth => include_str!("icons/bluetooth.svg"),
            Self::Boat => include_str!("icons/boat.svg"),
            Self::Body => include_str!("icons/body.svg"),
            Self::Bonfire => include_str!("icons/bonfire.svg"),
            Self::Book => include_str!("icons/book.svg"),
            Self::Bookmark => include_str!("icons/bookmark.svg"),
            Self::Bookmarks => include_str!("icons/bookmarks.svg"),
            Self::BowlingBall => include_str!("icons/bowling-ball.svg"),
            Self::Briefcase => include_str!("icons/briefcase.svg"),
            Self::Browsers => include_str!("icons/browsers.svg"),
            Self::Brush => include_str!("icons/brush.svg"),
            Self::Bug => include_str!("icons/bug.svg"),
            Self::Build => include_str!("icons/build.svg"),
            Self::Bulb => include_str!("icons/bulb.svg"),
            Self::Bus => include_str!("icons/bus.svg"),
            Self::Business => include_str!("icons/business.svg"),
            Self::Cafe => include_str!("icons/cafe.svg"),
            Self::Calculator => include_str!("icons/calculator.svg"),
            Self::CalendarClear => include_str!("icons/calendar-clear.svg"),
            Self::CalendarNumber => include_str!("icons/calendar-number.svg"),
            Self::Calendar => include_str!("icons/calendar.svg"),
            Self::Call => include_str!("icons/call.svg"),
            Self::CameraReverse => include_str!("icons/camera-reverse.svg"),
            Self::Camera => include_str!("icons/camera.svg"),
            Self::CarSport => include_str!("icons/car-sport.svg"),
            Self::Car => include_str!("icons/car.svg"),
            Self::Card => include_str!("icons/card.svg"),
            Self::CaretBackCircle => include_str!("icons/caret-back-circle.svg"),
            Self::CaretBack => include_str!("icons/caret-back.svg"),
            Self::CaretDownCircle => include_str!("icons/caret-down-circle.svg"),
            Self::CaretDown => include_str!("icons/caret-down.svg"),
            Self::CaretForwardCircle => include_str!("icons/caret-forward-circle.svg"),
            Self::CaretForward => include_str!("icons/caret-forward.svg"),
            Self::CaretUpCircle => include_str!("icons/caret-up-circle.svg"),
            Self::CaretUp => include_str!("icons/caret-up.svg"),
            Self::Cart => include_str!("icons/cart.svg"),
            Self::Cash => include_str!("icons/cash.svg"),
            Self::Cellular => include_str!("icons/cellular.svg"),
            Self::ChatboxEllipses => include_str!("icons/chatbox-ellipses.svg"),
            Self::Chatbox => include_str!("icons/chatbox.svg"),
            Self::ChatbubbleEllipses => include_str!("icons/chatbubble-ellipses.svg"),
            Self::Chatbubble => include_str!("icons/chatbubble.svg"),
            Self::Chatbubbles => include_str!("icons/chatbubbles.svg"),
            Self::Checkbox => include_str!("icons/checkbox.svg"),
            Self::CheckmarkCircle => include_str!("icons/checkmark-circle.svg"),
            Self::CheckmarkDoneCircle => include_str!("icons/checkmark-done-circle.svg"),
            Self::CheckmarkDone => include_str!("icons/checkmark-done.svg"),
            Self::Checkmark => include_str!("icons/checkmark.svg"),
            Self::ChevronBackCircle => include_str!("icons/chevron-back-circle.svg"),
            Self::ChevronBack => include_str!("icons/chevron-back.svg"),
            Self::ChevronCollapse => include_str!("icons/chevron-collapse.svg"),
            Self::ChevronDownCircle => include_str!("icons/chevron-down-circle.svg"),
            Self::ChevronDown => include_str!("icons/chevron-down.svg"),
            Self::ChevronExpand => include_str!("icons/chevron-expand.svg"),
            Self::ChevronForwardCircle => include_str!("icons/chevron-forward-circle.svg"),
            Self::ChevronForward => include_str!("icons/chevron-forward.svg"),
            Self::ChevronUpCircle => include_str!("icons/chevron-up-circle.svg"),
            Self::ChevronUp => include_str!("icons/chevron-up.svg"),
            Self::Clipboard => include_str!("icons/clipboard.svg"),
            Self::CloseCircle => include_str!("icons/close-circle.svg"),
            Self::Close => include_str!("icons/close.svg"),
            Self::CloudCircle => include_str!("icons/cloud-circle.svg"),
            Self::CloudDone => include_str!("icons/cloud-done.svg"),
            Self::CloudDownload => include_str!("icons/cloud-download.svg"),
            Self::CloudOffline => include_str!("icons/cloud-offline.svg"),
            Self::CloudUpload => include_str!("icons/cloud-upload.svg"),
            Self::Cloud => include_str!("icons/cloud.svg"),
            Self::CloudyNight => include_str!("icons/cloudy-night.svg"),
            Self::Cloudy => include_str!("icons/cloudy.svg"),
            Self::CodeDownload => include_str!("icons/code-download.svg"),
            Self::CodeSlash => include_str!("icons/code-slash.svg"),
            Self::CodeWorking => include_str!("icons/code-working.svg"),
            Self::Code => include_str!("icons/code.svg"),
            Self::Cog => include_str!("icons/cog.svg"),
            Self::ColorFill => include_str!("icons/color-fill.svg"),
            Self::ColorFilter => include_str!("icons/color-filter.svg"),
            Self::ColorPalette => include_str!("icons/color-palette.svg"),
            Self::ColorWand => include_str!("icons/color-wand.svg"),
            Self::Compass => include_str!("icons/compass.svg"),
            Self::Construct => include_str!("icons/construct.svg"),
            Self::Contract => include_str!("icons/contract.svg"),
            Self::Contrast => include_str!("icons/contrast.svg"),
            Self::Copy => include_str!("icons/copy.svg"),
            Self::Create => include_str!("icons/create.svg"),
            Self::Crop => include_str!("icons/crop.svg"),
            Self::Cube => include_str!("icons/cube.svg"),
            Self::Cut => include_str!("icons/cut.svg"),
            Self::Desktop => include_str!("icons/desktop.svg"),
            Self::Diamond => include_str!("icons/diamond.svg"),
            Self::Dice => include_str!("icons/dice.svg"),
            Self::Disc => include_str!("icons/disc.svg"),
            Self::DocumentAttach => include_str!("icons/document-attach.svg"),
            Self::DocumentLock => include_str!("icons/document-lock.svg"),
            Self::DocumentText => include_str!("icons/document-text.svg"),
            Self::Document => include_str!("icons/document.svg"),
            Self::Documents => include_str!("icons/documents.svg"),
            Self::Download => include_str!("icons/download.svg"),
            Self::Duplicate => include_str!("icons/duplicate.svg"),
            Self::Ear => include_str!("icons/ear.svg"),
            Self::Earth => include_str!("icons/earth.svg"),
            Self::Easel => include_str!("icons/easel.svg"),
            Self::Egg => include_str!("icons/egg.svg"),
            Self::Ellipse => include_str!("icons/ellipse.svg"),
            Self::EllipsisHorizontalCircle => include_str!("icons/ellipsis-horizontal-circle.svg"),
            Self::EllipsisHorizontal => include_str!("icons/ellipsis-horizontal.svg"),
            Self::EllipsisVerticalCircle => include_str!("icons/ellipsis-vertical-circle.svg"),
            Self::EllipsisVertical => include_str!("icons/ellipsis-vertical.svg"),
            Self::Enter => include_str!("icons/enter.svg"),
            Self::Exit => include_str!("icons/exit.svg"),
            Self::Expand => include_str!("icons/expand.svg"),
            Self::ExtensionPuzzle => include_str!("icons/extension-puzzle.svg"),
            Self::EyeOff => include_str!("icons/eye-off.svg"),
            Self::Eye => include_str!("icons/eye.svg"),
            Self::Eyedrop => include_str!("icons/eyedrop.svg"),
            Self::FastFood => include_str!("icons/fast-food.svg"),
            Self::Female => include_str!("icons/female.svg"),
            Self::FileTrayFull => include_str!("icons/file-tray-full.svg"),
            Self::FileTrayStacked => include_str!("icons/file-tray-stacked.svg"),
            Self::FileTray => include_str!("icons/file-tray.svg"),
            Self::Film => include_str!("icons/film.svg"),
            Self::FilterCircle => include_str!("icons/filter-circle.svg"),
            Self::Filter => include_str!("icons/filter.svg"),
            Self::FingerPrint => include_str!("icons/finger-print.svg"),
            Self::Fish => include_str!("icons/fish.svg"),
            Self::Fitness => include_str!("icons/fitness.svg"),
            Self::Flag => include_str!("icons/flag.svg"),
            Self::Flame => include_str!("icons/flame.svg"),
            Self::FlashOff => include_str!("icons/flash-off.svg"),
            Self::Flash => include_str!("icons/flash.svg"),
            Self::Flashlight => include_str!("icons/flashlight.svg"),
            Self::Flask => include_str!("icons/flask.svg"),
            Self::Flower => include_str!("icons/flower.svg"),
            Self::FolderOpen => include_str!("icons/folder-open.svg"),
            Self::Folder => include_str!("icons/folder.svg"),
            Self::Football => include_str!("icons/football.svg"),
            Self::Footsteps => include_str!("icons/footsteps.svg"),
            Self::Funnel => include_str!("icons/funnel.svg"),
            Self::GameController => include_str!("icons/game-controller.svg"),
            Self::Gift => include_str!("icons/gift.svg"),
            Self::GitBranch => include_str!("icons/git-branch.svg"),
            Self::GitCommit => include_str!("icons/git-commit.svg"),
            Self::GitCompare => include_str!("icons/git-compare.svg"),
            Self::GitMerge => include_str!("icons/git-merge.svg"),
            Self::GitNetwork => include_str!("icons/git-network.svg"),
            Self::GitPullRequest => include_str!("icons/git-pull-request.svg"),
            Self::Glasses => include_str!("icons/glasses.svg"),
            Self::Globe => include_str!("icons/globe.svg"),
            Self::Golf => include_str!("icons/golf.svg"),
            Self::Grid => include_str!("icons/grid.svg"),
            Self::Hammer => include_str!("icons/hammer.svg"),
            Self::HandLeft => include_str!("icons/hand-left.svg"),
            Self::HandRight => include_str!("icons/hand-right.svg"),
            Self::Happy => include_str!("icons/happy.svg"),
            Self::HardwareChip => include_str!("icons/hardware-chip.svg"),
            Self::Headset => include_str!("icons/headset.svg"),
            Self::HeartCircle => include_str!("icons/heart-circle.svg"),
            Self::HeartDislikeCircle => include_str!("icons/heart-dislike-circle.svg"),
            Self::HeartDislike => include_str!("icons/heart-dislike.svg"),
            Self::HeartHalf => include_str!("icons/heart-half.svg"),
            Self::Heart => include_str!("icons/heart.svg"),
            Self::HelpBuoy => include_str!("icons/help-buoy.svg"),
            Self::HelpCircle => include_str!("icons/help-circle.svg"),
            Self::Help => include_str!("icons/help.svg"),
            Self::Home => include_str!("icons/home.svg"),
            Self::Hourglass => include_str!("icons/hourglass.svg"),
            Self::IceCream => include_str!("icons/ice-cream.svg"),
            Self::IdCard => include_str!("icons/id-card.svg"),
            Self::Image => include_str!("icons/image.svg"),
            Self::Images => include_str!("icons/images.svg"),
            Self::Infinite => include_str!("icons/infinite.svg"),
            Self::InformationCircle => include_str!("icons/information-circle.svg"),
            Self::Information => include_str!("icons/information.svg"),
            Self::InvertMode => include_str!("icons/invert-mode.svg"),
            Self::Journal => include_str!("icons/journal.svg"),
            Self::Key => include_str!("icons/key.svg"),
            Self::Keypad => include_str!("icons/keypad.svg"),
            Self::Language => include_str!("icons/language.svg"),
            Self::Laptop => include_str!("icons/laptop.svg"),
            Self::Layers => include_str!("icons/layers.svg"),
            Self::Leaf => include_str!("icons/leaf.svg"),
            Self::Library => include_str!("icons/library.svg"),
            Self::Link => include_str!("icons/link.svg"),
            Self::ListCircle => include_str!("icons/list-circle.svg"),
            Self::List => include_str!("icons/list.svg"),
            Self::Locate => include_str!("icons/locate.svg"),
            Self::Location => include_str!("icons/location.svg"),
            Self::LockClosed => include_str!("icons/lock-closed.svg"),
            Self::LockOpen => include_str!("icons/lock-open.svg"),
            Self::LogIn => include_str!("icons/log-in.svg"),
            Self::LogOut => include_str!("icons/log-out.svg"),
            Self::LogoAlipay => include_str!("icons/logo-alipay.svg"),
            Self::LogoAmazon => include_str!("icons/logo-amazon.svg"),
            Self::LogoAmplify => include_str!("icons/logo-amplify.svg"),
            Self::LogoAndroid => include_str!("icons/logo-android.svg"),
            Self::LogoAngular => include_str!("icons/logo-angular.svg"),
            Self::LogoAppflow => include_str!("icons/logo-appflow.svg"),
            Self::LogoAppleAppstore => include_str!("icons/logo-apple-appstore.svg"),
            Self::LogoAppleAr => include_str!("icons/logo-apple-ar.svg"),
            Self::LogoApple => include_str!("icons/logo-apple.svg"),
            Self::LogoBehance => include_str!("icons/logo-behance.svg"),
            Self::LogoBitbucket => include_str!("icons/logo-bitbucket.svg"),
            Self::LogoBitcoin => include_str!("icons/logo-bitcoin.svg"),
            Self::LogoBuffer => include_str!("icons/logo-buffer.svg"),
            Self::LogoCapacitor => include_str!("icons/logo-capacitor.svg"),
            Self::LogoChrome => include_str!("icons/logo-chrome.svg"),
            Self::LogoClosedCaptioning => include_str!("icons/logo-closed-captioning.svg"),
            Self::LogoCodepen => include_str!("icons/logo-codepen.svg"),
            Self::LogoCss3 => include_str!("icons/logo-css3.svg"),
            Self::LogoDesignernews => include_str!("icons/logo-designernews.svg"),
            Self::LogoDeviantart => include_str!("icons/logo-deviantart.svg"),
            Self::LogoDiscord => include_str!("icons/logo-discord.svg"),
            Self::LogoDocker => include_str!("icons/logo-docker.svg"),
            Self::LogoDribbble => include_str!("icons/logo-dribbble.svg"),
            Self::LogoDropbox => include_str!("icons/logo-dropbox.svg"),
            Self::LogoEdge => include_str!("icons/logo-edge.svg"),
            Self::LogoElectron => include_str!("icons/logo-electron.svg"),
            Self::LogoEuro => include_str!("icons/logo-euro.svg"),
            Self::LogoFacebook => include_str!("icons/logo-facebook.svg"),
            Self::LogoFigma => include_str!("icons/logo-figma.svg"),
            Self::LogoFirebase => include_str!("icons/logo-firebase.svg"),
            Self::LogoFirefox => include_str!("icons/logo-firefox.svg"),
            Self::LogoFlickr => include_str!("icons/logo-flickr.svg"),
            Self::LogoFoursquare => include_str!("icons/logo-foursquare.svg"),
            Self::LogoGithub => include_str!("icons/logo-github.svg"),
            Self::LogoGitlab => include_str!("icons/logo-gitlab.svg"),
            Self::LogoGooglePlaystore => include_str!("icons/logo-google-playstore.svg"),
            Self::LogoGoogle => include_str!("icons/logo-google.svg"),
            Self::LogoHackernews => include_str!("icons/logo-hackernews.svg"),
            Self::LogoHtml5 => include_str!("icons/logo-html5.svg"),
            Self::LogoInstagram => include_str!("icons/logo-instagram.svg"),
            Self::LogoIonic => include_str!("icons/logo-ionic.svg"),
            Self::LogoIonitron => include_str!("icons/logo-ionitron.svg"),
            Self::LogoJavascript => include_str!("icons/logo-javascript.svg"),
            Self::LogoLaravel => include_str!("icons/logo-laravel.svg"),
            Self::LogoLinkedin => include_str!("icons/logo-linkedin.svg"),
            Self::LogoMarkdown => include_str!("icons/logo-markdown.svg"),
            Self::LogoMastodon => include_str!("icons/logo-mastodon.svg"),
            Self::LogoMedium => include_str!("icons/logo-medium.svg"),
            Self::LogoMicrosoft => include_str!("icons/logo-microsoft.svg"),
            Self::LogoNoSmoking => include_str!("icons/logo-no-smoking.svg"),
            Self::LogoNodejs => include_str!("icons/logo-nodejs.svg"),
            Self::LogoNpm => include_str!("icons/logo-npm.svg"),
            Self::LogoOctocat => include_str!("icons/logo-octocat.svg"),
            Self::LogoPaypal => include_str!("icons/logo-paypal.svg"),
            Self::LogoPinterest => include_str!("icons/logo-pinterest.svg"),
            Self::LogoPlaystation => include_str!("icons/logo-playstation.svg"),
            Self::LogoPwa => include_str!("icons/logo-pwa.svg"),
            Self::LogoPython => include_str!("icons/logo-python.svg"),
            Self::LogoReact => include_str!("icons/logo-react.svg"),
            Self::LogoReddit => include_str!("icons/logo-reddit.svg"),
            Self::LogoRss => include_str!("icons/logo-rss.svg"),
            Self::LogoSass => include_str!("icons/logo-sass.svg"),
            Self::LogoSkype => include_str!("icons/logo-skype.svg"),
            Self::LogoSlack => include_str!("icons/logo-slack.svg"),
            Self::LogoSnapchat => include_str!("icons/logo-snapchat.svg"),
            Self::LogoSoundcloud => include_str!("icons/logo-soundcloud.svg"),
            Self::LogoStackoverflow => include_str!("icons/logo-stackoverflow.svg"),
            Self::LogoSteam => include_str!("icons/logo-steam.svg"),
            Self::LogoStencil => include_str!("icons/logo-stencil.svg"),
            Self::LogoTableau => include_str!("icons/logo-tableau.svg"),
            Self::LogoTiktok => include_str!("icons/logo-tiktok.svg"),
            Self::LogoTrapeze => include_str!("icons/logo-trapeze.svg"),
            Self::LogoTumblr => include_str!("icons/logo-tumblr.svg"),
            Self::LogoTux => include_str!("icons/logo-tux.svg"),
            Self::LogoTwitch => include_str!("icons/logo-twitch.svg"),
            Self::LogoTwitter => include_str!("icons/logo-twitter.svg"),
            Self::LogoUsd => include_str!("icons/logo-usd.svg"),
            Self::LogoVenmo => include_str!("icons/logo-venmo.svg"),
            Self::LogoVercel => include_str!("icons/logo-vercel.svg"),
            Self::LogoVimeo => include_str!("icons/logo-vimeo.svg"),
            Self::LogoVk => include_str!("icons/logo-vk.svg"),
            Self::LogoVue => include_str!("icons/logo-vue.svg"),
            Self::LogoWebComponent => include_str!("icons/logo-web-component.svg"),
            Self::LogoWechat => include_str!("icons/logo-wechat.svg"),
            Self::LogoWhatsapp => include_str!("icons/logo-whatsapp.svg"),
            Self::LogoWindows => include_str!("icons/logo-windows.svg"),
            Self::LogoWordpress => include_str!("icons/logo-wordpress.svg"),
            Self::LogoX => include_str!("icons/logo-x.svg"),
            Self::LogoXbox => include_str!("icons/logo-xbox.svg"),
            Self::LogoXing => include_str!("icons/logo-xing.svg"),
            Self::LogoYahoo => include_str!("icons/logo-yahoo.svg"),
            Self::LogoYen => include_str!("icons/logo-yen.svg"),
            Self::LogoYoutube => include_str!("icons/logo-youtube.svg"),
            Self::Magnet => include_str!("icons/magnet.svg"),
            Self::MailOpen => include_str!("icons/mail-open.svg"),
            Self::MailUnread => include_str!("icons/mail-unread.svg"),
            Self::Mail => include_str!("icons/mail.svg"),
            Self::MaleFemale => include_str!("icons/male-female.svg"),
            Self::Male => include_str!("icons/male.svg"),
            Self::Man => include_str!("icons/man.svg"),
            Self::Map => include_str!("icons/map.svg"),
            Self::Medal => include_str!("icons/medal.svg"),
            Self::Medical => include_str!("icons/medical.svg"),
            Self::Medkit => include_str!("icons/medkit.svg"),
            Self::Megaphone => include_str!("icons/megaphone.svg"),
            Self::Menu => include_str!("icons/menu.svg"),
            Self::MicCircle => include_str!("icons/mic-circle.svg"),
            Self::MicOffCircle => include_str!("icons/mic-off-circle.svg"),
            Self::MicOff => include_str!("icons/mic-off.svg"),
            Self::Mic => include_str!("icons/mic.svg"),
            Self::Moon => include_str!("icons/moon.svg"),
            Self::Move => include_str!("icons/move.svg"),
            Self::MusicalNote => include_str!("icons/musical-note.svg"),
            Self::MusicalNotes => include_str!("icons/musical-notes.svg"),
            Self::NavigateCircle => include_str!("icons/navigate-circle.svg"),
            Self::Navigate => include_str!("icons/navigate.svg"),
            Self::Newspaper => include_str!("icons/newspaper.svg"),
            Self::NotificationsCircle => include_str!("icons/notifications-circle.svg"),
            Self::NotificationsOffCircle => include_str!("icons/notifications-off-circle.svg"),
            Self::NotificationsOff => include_str!("icons/notifications-off.svg"),
            Self::Notifications => include_str!("icons/notifications.svg"),
            Self::Nuclear => include_str!("icons/nuclear.svg"),
            Self::Nutrition => include_str!("icons/nutrition.svg"),
            Self::Open => include_str!("icons/open.svg"),
            Self::Options => include_str!("icons/options.svg"),
            Self::PaperPlane => include_str!("icons/paper-plane.svg"),
            Self::PartlySunny => include_str!("icons/partly-sunny.svg"),
            Self::PauseCircle => include_str!("icons/pause-circle.svg"),
            Self::Pause => include_str!("icons/pause.svg"),
            Self::Paw => include_str!("icons/paw.svg"),
            Self::Pencil => include_str!("icons/pencil.svg"),
            Self::PeopleCircle => include_str!("icons/people-circle.svg"),
            Self::People => include_str!("icons/people.svg"),
            Self::PersonAdd => include_str!("icons/person-add.svg"),
            Self::PersonCircle => include_str!("icons/person-circle.svg"),
            Self::PersonRemove => include_str!("icons/person-remove.svg"),
            Self::Person => include_str!("icons/person.svg"),
            Self::PhoneLandscape => include_str!("icons/phone-landscape.svg"),
            Self::PhonePortrait => include_str!("icons/phone-portrait.svg"),
            Self::PieChart => include_str!("icons/pie-chart.svg"),
            Self::Pin => include_str!("icons/pin.svg"),
            Self::Pint => include_str!("icons/pint.svg"),
            Self::Pizza => include_str!("icons/pizza.svg"),
            Self::Planet => include_str!("icons/planet.svg"),
            Self::PlayBackCircle => include_str!("icons/play-back-circle.svg"),
            Self::PlayBack => include_str!("icons/play-back.svg"),
            Self::PlayCircle => include_str!("icons/play-circle.svg"),
            Self::PlayForwardCircle => include_str!("icons/play-forward-circle.svg"),
            Self::PlayForward => include_str!("icons/play-forward.svg"),
            Self::PlaySkipBackCircle => include_str!("icons/play-skip-back-circle.svg"),
            Self::PlaySkipBack => include_str!("icons/play-skip-back.svg"),
            Self::PlaySkipForwardCircle => include_str!("icons/play-skip-forward-circle.svg"),
            Self::PlaySkipForward => include_str!("icons/play-skip-forward.svg"),
            Self::Play => include_str!("icons/play.svg"),
            Self::Podium => include_str!("icons/podium.svg"),
            Self::Power => include_str!("icons/power.svg"),
            Self::Pricetag => include_str!("icons/pricetag.svg"),
            Self::Pricetags => include_str!("icons/pricetags.svg"),
            Self::Print => include_str!("icons/print.svg"),
            Self::Prism => include_str!("icons/prism.svg"),
            Self::Pulse => include_str!("icons/pulse.svg"),
            Self::Push => include_str!("icons/push.svg"),
            Self::QrCode => include_str!("icons/qr-code.svg"),
            Self::RadioButtonOff => include_str!("icons/radio-button-off.svg"),
            Self::RadioButtonOn => include_str!("icons/radio-button-on.svg"),
            Self::Radio => include_str!("icons/radio.svg"),
            Self::Rainy => include_str!("icons/rainy.svg"),
            Self::Reader => include_str!("icons/reader.svg"),
            Self::Receipt => include_str!("icons/receipt.svg"),
            Self::Recording => include_str!("icons/recording.svg"),
            Self::RefreshCircle => include_str!("icons/refresh-circle.svg"),
            Self::Refresh => include_str!("icons/refresh.svg"),
            Self::ReloadCircle => include_str!("icons/reload-circle.svg"),
            Self::Reload => include_str!("icons/reload.svg"),
            Self::RemoveCircle => include_str!("icons/remove-circle.svg"),
            Self::Remove => include_str!("icons/remove.svg"),
            Self::ReorderFour => include_str!("icons/reorder-four.svg"),
            Self::ReorderThree => include_str!("icons/reorder-three.svg"),
            Self::ReorderTwo => include_str!("icons/reorder-two.svg"),
            Self::Repeat => include_str!("icons/repeat.svg"),
            Self::Resize => include_str!("icons/resize.svg"),
            Self::Restaurant => include_str!("icons/restaurant.svg"),
            Self::ReturnDownBack => include_str!("icons/return-down-back.svg"),
            Self::ReturnDownForward => include_str!("icons/return-down-forward.svg"),
            Self::ReturnUpBack => include_str!("icons/return-up-back.svg"),
            Self::ReturnUpForward => include_str!("icons/return-up-forward.svg"),
            Self::Ribbon => include_str!("icons/ribbon.svg"),
            Self::Rocket => include_str!("icons/rocket.svg"),
            Self::Rose => include_str!("icons/rose.svg"),
            Self::Sad => include_str!("icons/sad.svg"),
            Self::Save => include_str!("icons/save.svg"),
            Self::Scale => include_str!("icons/scale.svg"),
            Self::ScanCircle => include_str!("icons/scan-circle.svg"),
            Self::Scan => include_str!("icons/scan.svg"),
            Self::School => include_str!("icons/school.svg"),
            Self::SearchCircle => include_str!("icons/search-circle.svg"),
            Self::Search => include_str!("icons/search.svg"),
            Self::Send => include_str!("icons/send.svg"),
            Self::Server => include_str!("icons/server.svg"),
            Self::Settings => include_str!("icons/settings.svg"),
            Self::Shapes => include_str!("icons/shapes.svg"),
            Self::ShareSocial => include_str!("icons/share-social.svg"),
            Self::Share => include_str!("icons/share.svg"),
            Self::ShieldCheckmark => include_str!("icons/shield-checkmark.svg"),
            Self::ShieldHalf => include_str!("icons/shield-half.svg"),
            Self::Shield => include_str!("icons/shield.svg"),
            Self::Shirt => include_str!("icons/shirt.svg"),
            Self::Shuffle => include_str!("icons/shuffle.svg"),
            Self::Skull => include_str!("icons/skull.svg"),
            Self::Snow => include_str!("icons/snow.svg"),
            Self::Sparkles => include_str!("icons/sparkles.svg"),
            Self::Speedometer => include_str!("icons/speedometer.svg"),
            Self::Square => include_str!("icons/square.svg"),
            Self::StarHalf => include_str!("icons/star-half.svg"),
            Self::Star => include_str!("icons/star.svg"),
            Self::StatsChart => include_str!("icons/stats-chart.svg"),
            Self::StopCircle => include_str!("icons/stop-circle.svg"),
            Self::Stop => include_str!("icons/stop.svg"),
            Self::Stopwatch => include_str!("icons/stopwatch.svg"),
            Self::Storefront => include_str!("icons/storefront.svg"),
            Self::Subway => include_str!("icons/subway.svg"),
            Self::Sunny => include_str!("icons/sunny.svg"),
            Self::SwapHorizontal => include_str!("icons/swap-horizontal.svg"),
            Self::SwapVertical => include_str!("icons/swap-vertical.svg"),
            Self::SyncCircle => include_str!("icons/sync-circle.svg"),
            Self::Sync => include_str!("icons/sync.svg"),
            Self::TabletLandscape => include_str!("icons/tablet-landscape.svg"),
            Self::TabletPortrait => include_str!("icons/tablet-portrait.svg"),
            Self::Telescope => include_str!("icons/telescope.svg"),
            Self::Tennisball => include_str!("icons/tennisball.svg"),
            Self::Terminal => include_str!("icons/terminal.svg"),
            Self::Text => include_str!("icons/text.svg"),
            Self::Thermometer => include_str!("icons/thermometer.svg"),
            Self::ThumbsDown => include_str!("icons/thumbs-down.svg"),
            Self::ThumbsUp => include_str!("icons/thumbs-up.svg"),
            Self::Thunderstorm => include_str!("icons/thunderstorm.svg"),
            Self::Ticket => include_str!("icons/ticket.svg"),
            Self::Time => include_str!("icons/time.svg"),
            Self::Timer => include_str!("icons/timer.svg"),
            Self::Today => include_str!("icons/today.svg"),
            Self::Toggle => include_str!("icons/toggle.svg"),
            Self::TrailSign => include_str!("icons/trail-sign.svg"),
            Self::Train => include_str!("icons/train.svg"),
            Self::Transgender => include_str!("icons/transgender.svg"),
            Self::TrashBin => include_str!("icons/trash-bin.svg"),
            Self::Trash => include_str!("icons/trash.svg"),
            Self::TrendingDown => include_str!("icons/trending-down.svg"),
            Self::TrendingUp => include_str!("icons/trending-up.svg"),
            Self::Triangle => include_str!("icons/triangle.svg"),
            Self::Trophy => include_str!("icons/trophy.svg"),
            Self::Tv => include_str!("icons/tv.svg"),
            Self::Umbrella => include_str!("icons/umbrella.svg"),
            Self::Unlink => include_str!("icons/unlink.svg"),
            Self::VideocamOff => include_str!("icons/videocam-off.svg"),
            Self::Videocam => include_str!("icons/videocam.svg"),
            Self::VolumeHigh => include_str!("icons/volume-high.svg"),
            Self::VolumeLow => include_str!("icons/volume-low.svg"),
            Self::VolumeMedium => include_str!("icons/volume-medium.svg"),
            Self::VolumeMute => include_str!("icons/volume-mute.svg"),
            Self::VolumeOff => include_str!("icons/volume-off.svg"),
            Self::Walk => include_str!("icons/walk.svg"),
            Self::Wallet => include_str!("icons/wallet.svg"),
            Self::Warning => include_str!("icons/warning.svg"),
            Self::Watch => include_str!("icons/watch.svg"),
            Self::Water => include_str!("icons/water.svg"),
            Self::Wifi => include_str!("icons/wifi.svg"),
            Self::Wine => include_str!("icons/wine.svg"),
            Self::Woman => include_str!("icons/woman.svg"),
        }
    }
}
